# Nome do Workflow do GitHub Action
name: Generate Snake Animation

# Define quando a Action deve rodar
on:
  # Roda automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite que você rode essa Action manualmente pela aba "Actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão necessária para salvar os arquivos no repositório

    steps:
      # 1. Faz o checkout do seu repositório para que a Action possa acessá-lo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Gera os arquivos SVG da animação da cobra
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}
          
          # Lista de arquivos a serem gerados (tema claro e escuro)
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Envia os arquivos gerados para a branch "output"
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # A branch para onde os arquivos serão enviados
          target_branch: output
          # O diretório que contém os arquivos gerados no passo anterior
          build_dir: dist
        env:
          # Token de autenticação, gerado automaticamente pelo GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
